
#服务器端口和项目名称配置
server:
  port: 2233
eureka:
  client:
    service-Url:
      defaultZone: http://127.0.0.1:3100/eureka
#数据库配置
spring:
  application:
    name: com-yanshen-weibo
  redis:
    database: 0
    host: 192.168.123.47
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
  profiles:
    active: dev
  datasource:
    name: springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://218.89.171.137:31063/weibo?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 6d34761495ec289e
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 这里我使用了devtool热部署技术，这样就不需要每次都重启服务！！-->
  debug: false
  spring:
    devtools:
      restart:
        enabled: true  #设置开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  #配置Mapper.xml映射文件
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
    #  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #log:
  #info:
  #to: console
#  logging:
#    path: E/ims #日志文件路径
#    level:
#      root: info #日志级别 root表示所有包，也可以单独配置具体包 fatal error warn info debug trace off

