server:
  port: 3006
  servlet:
    context-path:
spring:
  application:
    name: com.yanshen.generator
  redis:
    database: 0
    host: 192.168.0.99
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
  profiles:
    active: dev
  datasource:
    name: springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://61.139.65.135:31063/weibo?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 6d34761495ec289e
    url: jdbc:mysql://192.168.2.99:3307/isp-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: zksk666
    # ??druid???
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl